services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    gpus: all   # <-- comment this out if wanna use on a machine without nvidia gpu